- name: templating manifest {{ k8s_amaizfinance_redis_cr_manifest_template }}
  template:
    src: "{{ k8s_amaizfinance_redis_cr_manifest_template }}"
    dest: "/root/{{ k8s_amaizfinance_redis_cr_manifest_file }}"

- name: apply {{ k8s_amaizfinance_redis_cr_manifest_file }}
  command: kubectl apply -f /root/{{ k8s_amaizfinance_redis_cr_manifest_file }} -n {{ k8s_amaizfinance_redis_cr_namespace }}
  # TODO: when you use command module, it's mandatory to use register and changed_when directives.
